source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-include-cache"
  gem "jekyll-sitemap"
  gem "jekyll-feed"
  gem "jekyll-remote-theme"
end

gem "tzinfo-data"
gem "wdm", "~> 0.1.0" if Gem.win_platform?
